// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBab1YXi55R75GyLTmGCR8FhiZixRsaexs',
    appId: '1:91948591827:web:299fdd6d8dcd36b51b8226',
    messagingSenderId: '91948591827',
    projectId: 'fitnessapp-3f647',
    authDomain: 'fitnessapp-3f647.firebaseapp.com',
    storageBucket: 'fitnessapp-3f647.firebasestorage.app',
    measurementId: 'G-M4MZ34VE1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6XHHPY6ReE5-b6trLA4ujbcEjAwTQHgs',
    appId: '1:91948591827:android:3dee2ff94c39001d1b8226',
    messagingSenderId: '91948591827',
    projectId: 'fitnessapp-3f647',
    storageBucket: 'fitnessapp-3f647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwkpGshdjjjWTwqMUxDxaddjmE4B6J5O8',
    appId: '1:91948591827:ios:49ebe00ccc18198b1b8226',
    messagingSenderId: '91948591827',
    projectId: 'fitnessapp-3f647',
    storageBucket: 'fitnessapp-3f647.firebasestorage.app',
    iosBundleId: 'com.rw.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwkpGshdjjjWTwqMUxDxaddjmE4B6J5O8',
    appId: '1:91948591827:ios:49ebe00ccc18198b1b8226',
    messagingSenderId: '91948591827',
    projectId: 'fitnessapp-3f647',
    storageBucket: 'fitnessapp-3f647.firebasestorage.app',
    iosBundleId: 'com.rw.fitnessapp',
  );

}